--*********************************************************************************************************************--
-- PostgreSQL identity column
--GENERATED AS IDENTITY  allows you to automatically assign a unique number to a column.
--The GENERATED AS IDENTITY constraint is the SQL standard-conforming variant of the good old SERIAL column.
--PostgreSQL allows a table to have more than one identity column. 
--Like the SERIAL, the GENERATED AS IDENTITY constraint also uses the SEQUENCE object internally.
--*********************************************************************************************************************--
--1) GENERATED ALWAYS example
--First, create a table named color with the color_id as the identity column:


CREATE TABLE color (
    color_id INT GENERATED ALWAYS AS IDENTITY,
    color_name VARCHAR NOT NULL
);
--Second, insert a new row into the color table:
INSERT INTO color(color_name)
VALUES ('Red');
--Third, insert a new row by supplying values for both color_id and color_name columns:
-- ERROR:  cannot insert a non-DEFAULT value into column "color_id"
-- Column "color_id" is an identity column defined as GENERATED ALWAYS. 

-- SQL state: 428C9
-- Detail: Column "color_id" is an identity column defined as GENERATED ALWAYS.
-- Hint: Use OVERRIDING SYSTEM VALUE to override.

INSERT INTO color (color_id, color_name)
VALUES (2, 'Green');
--To fix the error, you can use the OVERRIDING SYSTEM VALUE clause as follows:
INSERT INTO color (color_id, color_name)
OVERRIDING SYSTEM VALUE
VALUES(2, 'Green');

--2) GENERATED BY DEFAULT AS IDENTITY example
--First, create a table 
CREATE TABLE shapes (
    shape_id INT GENERATED BY DEFAULT AS IDENTITY,
    shape_name VARCHAR NOT NULL
);
--Second, insert a new row into the shapes table:
INSERT INTO shapes (shape_name)
VALUES ('Square');
--Third, insert another row with a value for the shape_id column:
INSERT INTO shapes (shape_id, shape_name)
VALUES (2, 'Rectangle');

--3) Sequence options example you can specify the starting value and the increment 

CREATE TABLE days (
    day_id INT GENERATED BY DEFAULT AS IDENTITY
    (START WITH 10 INCREMENT BY 10),
    day_name VARCHAR NOT NULL
);
--The system-generated value for the day_id column starts with 10 and the increment value is also 10.
INSERT INTO days (day_name)
VALUES ('Monday');
--The value of the day_id of the second row is 20 because of the increment option.


INSERT INTO days (day_name)
VALUES ('Tuesday');

--Adding an identity column to an existing table
--create a new table
CREATE TABLE shape (
    shape_id INT NOT NULL,
    shape_name VARCHAR NOT NULL
);
--Second, change the shape_id column to the identity column:
---Note that the shape_id needs to have the NOT NULL constraint so that it 
--can be changed to an identity column. Otherwise, you’ll get the following error ERROR:  column "shape_id" of relation "shape" must be declared NOT NULL before identity can be added
--SQL state: 55000
ALTER TABLE shape
ALTER COLUMN shape_id ADD GENERATED ALWAYS AS IDENTITY;

dvdrental=# \d shape
                                 Table "public.shape"
   Column   |       Type        | Collation | Nullable |           Default            
------------+-------------------+-----------+----------+------------------------------
 shape_id   | integer           |           | not null | generated always as identity
 shape_name | character varying |           | not null | 


--Changing an identity column
ALTER TABLE shape
ALTER COLUMN shape_id SET GENERATED BY DEFAULT;

dvdrental=# \d shape
                                   Table "public.shape"
   Column   |       Type        | Collation | Nullable |             Default              
------------+-------------------+-----------+----------+----------------------------------
 shape_id   | integer           |           | not null | generated by default as identity
 shape_name | character varying |           | not null | 

 --Removing the GENERATED AS IDENTITY constraint

 ALTER TABLE shape
ALTER COLUMN shape_id
DROP IDENTITY IF EXISTS;
dvdrental=# \d shape
                      Table "public.shape"
   Column   |       Type        | Collation | Nullable | Default 
------------+-------------------+-----------+----------+---------
 shape_id   | integer           |           | not null | 
 shape_name | character varying |           | not null | 